package models

data class KeyCode(
    val label: String,
    val code: String
) {
    companion object {
        val all: List<KeyCode> = listOf(
            KeyCode("0 key", "KEYCODE_0"),
            KeyCode("1 key", "KEYCODE_1"),
            KeyCode("2 key", "KEYCODE_2"),
            KeyCode("3 key", "KEYCODE_3"),
            KeyCode("3D Mode key", "KEYCODE_3D_MODE"),
            KeyCode("4 key", "KEYCODE_4"),
            KeyCode("5 key", "KEYCODE_5"),
            KeyCode("6 key", "KEYCODE_6"),
            KeyCode("7 key", "KEYCODE_7"),
            KeyCode("8 key", "KEYCODE_8"),
            KeyCode("9 key", "KEYCODE_9"),
            KeyCode("A key", "KEYCODE_A"),
            KeyCode("A Button key", "KEYCODE_BUTTON_A"),
            KeyCode("Analog Terrestrial key", "KEYCODE_TV_TERRESTRIAL_ANALOG"),
            KeyCode("Antenna/Cable key", "KEYCODE_TV_ANTENNA_CABLE"),
            KeyCode("App switch key", "KEYCODE_APP_SWITCH"),
            KeyCode("Assist key", "KEYCODE_ASSIST"),
            KeyCode("Audio description key", "KEYCODE_TV_AUDIO_DESCRIPTION"),
            KeyCode("Audio description mixing volume down key", "KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN"),
            KeyCode("Audio description mixing volume up key", "KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP"),
            KeyCode("Audio Track key", "KEYCODE_MEDIA_AUDIO_TRACK"),
            KeyCode("A/V Receiver input key", "KEYCODE_AVR_INPUT"),
            KeyCode("A/V Receiver power key", "KEYCODE_AVR_POWER"),
            KeyCode("B key", "KEYCODE_B"),
            KeyCode("B Button key", "KEYCODE_BUTTON_B"),
            KeyCode("Back key", "KEYCODE_BACK"),
            KeyCode("Backspace key", "KEYCODE_DEL"),
            KeyCode("Blue \"programmable\" key", "KEYCODE_PROG_BLUE"),
            KeyCode("Bookmark key", "KEYCODE_BOOKMARK"),
            KeyCode("Break / Pause key", "KEYCODE_BREAK"),
            KeyCode("Brightness Down key", "KEYCODE_BRIGHTNESS_DOWN"),
            KeyCode("Brightness Up key", "KEYCODE_BRIGHTNESS_UP"),
            KeyCode("BS key", "KEYCODE_TV_SATELLITE_BS"),
            KeyCode("BS/CS key", "KEYCODE_TV_SATELLITE_SERVICE"),
            KeyCode("C key", "KEYCODE_C"),
            KeyCode("C Button key", "KEYCODE_BUTTON_C"),
            KeyCode("Calculator special function key", "KEYCODE_CALCULATOR"),
            KeyCode("Calendar special function key", "KEYCODE_CALENDAR"),
            KeyCode("Call key", "KEYCODE_CALL"),
            KeyCode("Camera key", "KEYCODE_CAMERA"),
            KeyCode("Camera Focus key", "KEYCODE_FOCUS"),
            KeyCode("Caps Lock key", "KEYCODE_CAPS_LOCK"),
            KeyCode("Channel down key", "KEYCODE_CHANNEL_DOWN"),
            KeyCode("Channel up key", "KEYCODE_CHANNEL_UP"),
            KeyCode("Clear key", "KEYCODE_CLEAR"),
            KeyCode("Close media key", "KEYCODE_MEDIA_CLOSE"),
            KeyCode("Component #1 key", "KEYCODE_TV_INPUT_COMPONENT_1"),
            KeyCode("Component #2 key", "KEYCODE_TV_INPUT_COMPONENT_2"),
            KeyCode("Composite #1 key", "KEYCODE_TV_INPUT_COMPOSITE_1"),
            KeyCode("Composite #2 key", "KEYCODE_TV_INPUT_COMPOSITE_2"),
            KeyCode("Contacts special function key", "KEYCODE_CONTACTS"),
            KeyCode("Contents menu key", "KEYCODE_TV_CONTENTS_MENU"),
            KeyCode("Copy key", "KEYCODE_COPY"),
            KeyCode("CS key", "KEYCODE_TV_SATELLITE_CS"),
            KeyCode("Cut key", "KEYCODE_CUT"),
            KeyCode("D key", "KEYCODE_D"),
            KeyCode("Digital Terrestrial key", "KEYCODE_TV_TERRESTRIAL_DIGITAL"),
            KeyCode("Directional Pad Center key", "KEYCODE_DPAD_CENTER"),
            KeyCode("Directional Pad Down key", "KEYCODE_DPAD_DOWN"),
            KeyCode("Directional Pad Down-Left key", "KEYCODE_DPAD_DOWN_LEFT"),
            KeyCode("Directional Pad Down-Right key", "KEYCODE_DPAD_DOWN_RIGHT"),
            KeyCode("Directional Pad Left key", "KEYCODE_DPAD_LEFT"),
            KeyCode("Directional Pad Right key", "KEYCODE_DPAD_RIGHT"),
            KeyCode("Directional Pad Up key", "KEYCODE_DPAD_UP"),
            KeyCode("Directional Pad Up-Left key", "KEYCODE_DPAD_UP_LEFT"),
            KeyCode("Directional Pad Up-Right key", "KEYCODE_DPAD_UP_RIGHT"),
            KeyCode("DVR key", "KEYCODE_DVR"),
            KeyCode("E key", "KEYCODE_E"),
            KeyCode("Eject media key", "KEYCODE_MEDIA_EJECT"),
            KeyCode("End Call key", "KEYCODE_ENDCALL"),
            KeyCode("End Movement key", "KEYCODE_MOVE_END"),
            KeyCode("Enter key", "KEYCODE_ENTER"),
            KeyCode("Envelope special function key", "KEYCODE_ENVELOPE"),
            KeyCode("Escape key", "KEYCODE_ESCAPE"),
            KeyCode("Explorer special function key", "KEYCODE_EXPLORER"),
            KeyCode("F key", "KEYCODE_F"),
            KeyCode("Fast Forward media key", "KEYCODE_MEDIA_FAST_FORWARD"),
            KeyCode("Forward key", "KEYCODE_FORWARD"),
            KeyCode("Forward Delete key", "KEYCODE_FORWARD_DEL"),
            KeyCode("Function key", "KEYCODE_FUNCTION"),
            KeyCode("F1 key", "KEYCODE_F1"),
            KeyCode("F10 key", "KEYCODE_F10"),
            KeyCode("F11 key", "KEYCODE_F11"),
            KeyCode("F12 key", "KEYCODE_F12"),
            KeyCode("F2 key", "KEYCODE_F2"),
            KeyCode("F3 key", "KEYCODE_F3"),
            KeyCode("F4 key", "KEYCODE_F4"),
            KeyCode("F5 key", "KEYCODE_F5"),
            KeyCode("F6 key", "KEYCODE_F6"),
            KeyCode("F7 key", "KEYCODE_F7"),
            KeyCode("F8 key", "KEYCODE_F8"),
            KeyCode("F9 key", "KEYCODE_F9"),
            KeyCode("G key", "KEYCODE_G"),
            KeyCode("Generic Game Pad Button #1", "KEYCODE_BUTTON_1"),
            KeyCode("Generic Game Pad Button #10", "KEYCODE_BUTTON_10"),
            KeyCode("Generic Game Pad Button #11", "KEYCODE_BUTTON_11"),
            KeyCode("Generic Game Pad Button #12", "KEYCODE_BUTTON_12"),
            KeyCode("Generic Game Pad Button #13", "KEYCODE_BUTTON_13"),
            KeyCode("Generic Game Pad Button #14", "KEYCODE_BUTTON_14"),
            KeyCode("Generic Game Pad Button #15", "KEYCODE_BUTTON_15"),
            KeyCode("Generic Game Pad Button #16", "KEYCODE_BUTTON_16"),
            KeyCode("Generic Game Pad Button #2", "KEYCODE_BUTTON_2"),
            KeyCode("Generic Game Pad Button #3", "KEYCODE_BUTTON_3"),
            KeyCode("Generic Game Pad Button #4", "KEYCODE_BUTTON_4"),
            KeyCode("Generic Game Pad Button #5", "KEYCODE_BUTTON_5"),
            KeyCode("Generic Game Pad Button #6", "KEYCODE_BUTTON_6"),
            KeyCode("Generic Game Pad Button #7", "KEYCODE_BUTTON_7"),
            KeyCode("Generic Game Pad Button #8", "KEYCODE_BUTTON_8"),
            KeyCode("Generic Game Pad Button #9", "KEYCODE_BUTTON_9"),
            KeyCode("Generic Game Pad Button #1", "KEYCODE_BUTTON_1"),
            KeyCode("Generic Game Pad Button #1", "KEYCODE_BUTTON_1"),
            KeyCode("Generic Game Pad Button #1", "KEYCODE_BUTTON_1"),
            KeyCode("Generic stem key 1 for Wear", "KEYCODE_STEM_1"),
            KeyCode("Generic stem key 2 for Wear", "KEYCODE_STEM_2"),
            KeyCode("Generic stem key 3 for Wear", "KEYCODE_STEM_3"),
            KeyCode("Green \"programmable\" key", "KEYCODE_PROG_BLUE"),
            KeyCode("Guide key", "KEYCODE_GUIDE"),
            KeyCode("H key", "KEYCODE_H"),
            KeyCode("HDMI #1 key", "KEYCODE_TV_INPUT_HDMI_1"),
            KeyCode("HDMI #2 key", "KEYCODE_TV_INPUT_HDMI_2"),
            KeyCode("HDMI #3 key", "KEYCODE_TV_INPUT_HDMI_3"),
            KeyCode("HDMI #4 key", "KEYCODE_TV_INPUT_HDMI_4"),
            KeyCode("Headset Hook key", "KEYCODE_HEADSETHOOK"),
            KeyCode("Help key", "KEYCODE_HELP"),
            KeyCode("Home key", "KEYCODE_HOME"),
            KeyCode("Home Movement key", "KEYCODE_MOVE_HOME"),
            KeyCode("I key", "KEYCODE_I"),
            KeyCode("Info key", "KEYCODE_INFO"),
            KeyCode("Insert key", "KEYCODE_INSERT"),
            KeyCode("J key", "KEYCODE_J"),
            KeyCode("Japanese alphanumeric key", "KEYCODE_EISU"),
            KeyCode("Japanese conversion key", "KEYCODE_HENKAN"),
            KeyCode("Japanese full-width / half-width key", "KEYCODE_ZENKAKU_HANKAKU"),
            KeyCode("Japanese kana key", "KEYCODE_KANA"),
            KeyCode("Japanese katakana / hiragana key", "KEYCODE_KATAKANA_HIRAGANA"),
            KeyCode("Japanese non-conversion key", "KEYCODE_MUHENKAN"),
            KeyCode("Japanese Ro key", "KEYCODE_RO"),
            KeyCode("Japanese Yen key", "KEYCODE_YEN"),
            KeyCode("K key", "KEYCODE_K"),
            KeyCode("L key", "KEYCODE_L"),
            KeyCode("Language Switch key", "KEYCODE_LANGUAGE_SWITCH"),
            KeyCode("Last Channel key", "KEYCODE_LAST_CHANNEL"),
            KeyCode("L1 Button key", "KEYCODE_BUTTON_L1"),
            KeyCode("L2 Button key", "KEYCODE_BUTTON_L2"),
            KeyCode("Left Alt modifier key", "KEYCODE_ALT_LEFT"),
            KeyCode("Left Control modifier key", "KEYCODE_CTRL_LEFT"),
            KeyCode("Left Meta modifier key", "KEYCODE_META_LEFT"),
            KeyCode("Left Shift modifier key", "KEYCODE_SHIFT_LEFT"),
            KeyCode("Left Thumb Button key", "KEYCODE_BUTTON_THUMBL"),
            KeyCode("M key", "KEYCODE_M"),
            KeyCode("Manner Mode key", "KEYCODE_MANNER_MODE"),
            KeyCode("Mode Button key", "KEYCODE_BUTTON_MODE"),
            KeyCode("Media context menu key", "KEYCODE_TV_MEDIA_CONTEXT_MENU"),
            KeyCode("Media Top Menu key", "KEYCODE_MEDIA_TOP_MENU"),
            KeyCode("Menu key", "KEYCODE_MENU"),
            KeyCode("Music special function key", "KEYCODE_MUSIC"),
            KeyCode("Mute key", "KEYCODE_MUTE"),
            KeyCode("N key", "KEYCODE_N"),
            KeyCode("Navigate in key", "KEYCODE_NAVIGATE_IN"),
            KeyCode("Navigate out key", "KEYCODE_NAVIGATE_OUT"),
            KeyCode("Navigate to next key", "KEYCODE_NAVIGATE_NEXT"),
            KeyCode("Navigate to previous key", "KEYCODE_NAVIGATE_PREVIOUS"),
            KeyCode("Notification key", "KEYCODE_NOTIFICATION"),
            KeyCode("Number entry key", "KEYCODE_TV_NUMBER_ENTRY"),
            KeyCode("Number modifier key", "KEYCODE_NUM"),
            KeyCode("Numeric keypad Enter key", "KEYCODE_NUMPAD_ENTER"),
            KeyCode("Numeric keypad 0 key", "KEYCODE_NUMPAD_0"),
            KeyCode("Numeric keypad 1 key", "KEYCODE_NUMPAD_1"),
            KeyCode("Numeric keypad 2 key", "KEYCODE_NUMPAD_2"),
            KeyCode("Numeric keypad 3 key", "KEYCODE_NUMPAD_3"),
            KeyCode("Numeric keypad 4 key", "KEYCODE_NUMPAD_4"),
            KeyCode("Numeric keypad 5 key", "KEYCODE_NUMPAD_5"),
            KeyCode("Numeric keypad 6 key", "KEYCODE_NUMPAD_6"),
            KeyCode("Numeric keypad 7 key", "KEYCODE_NUMPAD_7"),
            KeyCode("Numeric keypad 8 key", "KEYCODE_NUMPAD_8"),
            KeyCode("Numeric keypad 9 key", "KEYCODE_NUMPAD_9"),
            KeyCode("Numeric keypad + key", "KEYCODE_NUMPAD_ADD"),
            KeyCode("Numeric keypad , key", "KEYCODE_NUMPAD_COMMA"),
            KeyCode("Numeric keypad / key", "KEYCODE_NUMPAD_DIVIDE"),
            KeyCode("Numeric keypad . key", "KEYCODE_NUMPAD_DOT"),
            KeyCode("Numeric keypad = key", "KEYCODE_NUMPAD_EQUALS"),
            KeyCode("Numeric keypad ( key", "KEYCODE_NUMPAD_LEFT_PAREN"),
            KeyCode("Numeric keypad * key", "KEYCODE_NUMPAD_MULTIPLY"),
            KeyCode("Numeric keypad ) key", "KEYCODE_NUMPAD_RIGHT_PAREN"),
            KeyCode("Numeric keypad - key", "KEYCODE_NUMPAD_SUBTRACT"),
            KeyCode("Num Lock key", "KEYCODE_NUM_LOCK"),
            KeyCode("O key", "KEYCODE_O"),
            KeyCode("P key", "KEYCODE_P"),
            KeyCode("Page Down key", "KEYCODE_PAGE_DOWN"),
            KeyCode("Page Up key", "KEYCODE_PAGE_UP"),
            KeyCode("Pairing key", "KEYCODE_PAIRING"),
            KeyCode("Paste key", "KEYCODE_PASTE"),
            KeyCode("Pause media key", "KEYCODE_MEDIA_PAUSE"),
            KeyCode("Picture Symbols modifier key", "KEYCODE_PICTSYMBOLS"),
            KeyCode("Play media key", "KEYCODE_MEDIA_PLAY"),
            KeyCode("Play Next media key", "KEYCODE_MEDIA_NEXT"),
            KeyCode("Play Previous media key", "KEYCODE_MEDIA_PREVIOUS"),
            KeyCode("Play/Pause media key", "KEYCODE_MEDIA_PLAY_PAUSE"),
            KeyCode("Power key", "KEYCODE_POWER"),
            KeyCode("Primary stem key for Wear", "KEYCODE_STEM_PRIMARY"),
            KeyCode("Profile Switch key", "KEYCODE_PROFILE_SWITCH"),
            KeyCode("Q key", "KEYCODE_Q"),
            KeyCode("R key", "KEYCODE_R"),
            KeyCode("Radio key", "KEYCODE_TV_RADIO_SERVICE"),
            KeyCode("Record media key", "KEYCODE_MEDIA_RECORD"),
            KeyCode("Red \"programmable\" key", "KEYCODE_PROG_RED"),
            KeyCode("Refresh key", "KEYCODE_REFRESH"),
            KeyCode("Rewind media key", "KEYCODE_MEDIA_REWIND"),
            KeyCode("Right Alt modifier key", "KEYCODE_ALT_RIGHT"),
            KeyCode("Right Control modifier key", "KEYCODE_CTRL_RIGHT"),
            KeyCode("Right Meta modifier key", "KEYCODE_META_RIGHT"),
            KeyCode("Right Shift modifier key", "KEYCODE_SHIFT_RIGHT"),
            KeyCode("Right Thumb Button key", "KEYCODE_BUTTON_THUMBR"),
            KeyCode("R1 Button key", "KEYCODE_BUTTON_R1"),
            KeyCode("R2 Button key", "KEYCODE_BUTTON_R2"),
            KeyCode("S key", "KEYCODE_S"),
            KeyCode("Satellite key", "KEYCODE_TV_SATELLITE"),
            KeyCode("Scroll Lock key", "KEYCODE_SCROLL_LOCK"),
            KeyCode("Search key", "KEYCODE_SEARCH"),
            KeyCode("Select Button key", "KEYCODE_BUTTON_SELECT"),
            KeyCode("Settings key", "KEYCODE_SETTINGS"),
            KeyCode("Set-top-box input key", "KEYCODE_STB_INPUT"),
            KeyCode("Set-top-box power key", "KEYCODE_STB_POWER"),
            KeyCode("Show all apps", "KEYCODE_ALL_APPS"),
            KeyCode("Skip backward media key", "KEYCODE_MEDIA_SKIP_BACKWARD"),
            KeyCode("Skip forward media key", "KEYCODE_MEDIA_SKIP_FORWARD"),
            KeyCode("Sleep key", "KEYCODE_SLEEP"),
            KeyCode("Soft Left key", "KEYCODE_SOFT_LEFT"),
            KeyCode("Soft Right key", "KEYCODE_SOFT_RIGHT"),
            KeyCode("Soft Sleep key", "KEYCODE_SOFT_SLEEP"),
            KeyCode("Space key", "KEYCODE_SPACE"),
            KeyCode("Start Button key", "KEYCODE_BUTTON_START"),
            KeyCode("Step backward media key", "KEYCODE_MEDIA_STEP_BACKWARD"),
            KeyCode("Step forward media key", "KEYCODE_MEDIA_STEP_FORWARD"),
            KeyCode("Stop media key", "KEYCODE_MEDIA_STOP"),
            KeyCode("Switch Charset modifier key", "KEYCODE_SWITCH_CHARSET"),
            KeyCode("Symbol modifier key", "KEYCODE_SYM"),
            KeyCode("System Navigation Down key", "KEYCODE_SYSTEM_NAVIGATION_DOWN"),
            KeyCode("System Navigation Left key", "KEYCODE_SYSTEM_NAVIGATION_LEFT"),
            KeyCode("System Navigation Right key", "KEYCODE_SYSTEM_NAVIGATION_RIGHT"),
            KeyCode("System Navigation Up key", "KEYCODE_SYSTEM_NAVIGATION_UP"),
            KeyCode("System Request / Print Screen key", "KEYCODE_SYSRQ"),
            KeyCode("T key", "KEYCODE_T"),
            KeyCode("Tab key", "KEYCODE_TAB"),
            KeyCode("Teletext key", "KEYCODE_TV_TELETEXT"),
            KeyCode("Thumbs down key", "KEYCODE_THUMBS_DOWN"),
            KeyCode("Thumbs up key", "KEYCODE_THUMBS_UP"),
            KeyCode("Timer programming key", "KEYCODE_TV_TIMER_PROGRAMMING"),
            KeyCode("Toggle captions key", "KEYCODE_CAPTIONS"),
            KeyCode("Toggle Network key", "KEYCODE_TV_NETWORK"),
            KeyCode("TV key", "KEYCODE_TV"),
            KeyCode("TV data service key", "KEYCODE_TV_DATA_SERVICE"),
            KeyCode("TV input key", "KEYCODE_TV_INPUT"),
            KeyCode("TV power key", "KEYCODE_TV_POWER"),
            KeyCode("U key", "KEYCODE_U"),
            KeyCode("Unknown key code", "KEYCODE_UNKNOWN"),
            KeyCode("V key", "KEYCODE_V"),
            KeyCode("VGA #1 key", "KEYCODE_TV_INPUT_VGA_1"),
            KeyCode("Voice Assist key", "KEYCODE_VOICE_ASSIST"),
            KeyCode("Volume Down key", "KEYCODE_VOLUME_DOWN"),
            KeyCode("Volume Mute key", "KEYCODE_VOLUME_MUTE"),
            KeyCode("Volume Up key", "KEYCODE_VOLUME_UP"),
            KeyCode("W key", "KEYCODE_W"),
            KeyCode("Wakeup key", "KEYCODE_WAKEUP"),
            KeyCode("Window key", "KEYCODE_WINDOW"),
            KeyCode("X key", "KEYCODE_X"),
            KeyCode("X Button key", "KEYCODE_BUTTON_X"),
            KeyCode("Y key", "KEYCODE_Y"),
            KeyCode("Y Button key", "KEYCODE_BUTTON_Y"),
            KeyCode("Yellow \"programmable\" key", "KEYCODE_PROG_YELLOW"),
            KeyCode("Z key", "KEYCODE_Z"),
            KeyCode("Z Button key", "KEYCODE_BUTTON_Z"),
            KeyCode("Zoom in key", "KEYCODE_ZOOM_IN"),
            KeyCode("Zoom mode key", "KEYCODE_TV_ZOOM_MODE"),
            KeyCode("Zoom out key", "KEYCODE_ZOOM_OUT"),
            KeyCode("\" key", "KEYCODE_APOSTROPHE"),
            KeyCode("@ key", "KEYCODE_AT"),
            KeyCode("\\ key", "KEYCODE_BACKSLASH"),
            KeyCode(", key", "KEYCODE_COMMA"),
            KeyCode("= key", "KEYCODE_EQUALS"),
            KeyCode("` key", "KEYCODE_GRAVE"),
            KeyCode("[ key", "KEYCODE_LEFT_BRACKET"),
            KeyCode("- key", "KEYCODE_MINUS"),
            KeyCode(". key", "KEYCODE_PERIOD"),
            KeyCode("+ key", "KEYCODE_PLUS"),
            KeyCode("# key", "KEYCODE_POUND"),
            KeyCode("] key", "KEYCODE_RIGHT_BRACKET"),
            KeyCode("; key", "KEYCODE_SEMICOLON"),
            KeyCode("/ key", "KEYCODE_SLASH"),
            KeyCode("* key", "KEYCODE_STAR"),
        ).sortedBy { it.label }
    }
}
